### ISSUE TITLE
Put.re stopped working

### ISSUE THREAD

**Issue by filiptronicek** [sean-clayton/fotup#16]
The unexpected shutdown of the put.re API rendered this app broken. I think it would be nice either replacing the API provider or letting the users of the site know what's up.

**Comment by sean-clayton** [comment]
@filiptronicek Yeah, been meaning to get around to this--I'll look up some other possible APIs, but there's an issue of pre-existing images that use the `fotup.app` URL, but I'll see if there's a way around that

**Comment by sean-clayton** [comment]
For right now we are just going to display a warning on the homepage until I can find a suitable API and work out potential issues with backwards-compatibility with images from the old API

**Comment by filiptronicek** [comment]
What about [catbox.moe](https://catbox.moe/tools.php)?
